Repository EleutherAI/lm-evaluation-harness, pull requests merged in 2024-02, with the labels that each got.

#1227 Expand docs, update CITATION.bib
  README.md
  docs/CONTRIBUTING.md
Labels: documentation

#1364 Support for Inf2 optimum class [WIP]
  README.md
  lm_eval/models/__init__.py
  lm_eval/models/neuron_optimum.py
  pyproject.toml
  tests/models/test_neuron_optimum.py
Labels: feature request

#1371 Fix confusing `write_out.py` instructions in README
  README.md
Labels: documentation

#1390 Use Pooled rather than Combined Variance for calculating stderr of task groupings
  lm_eval/api/metrics.py
  lm_eval/evaluator.py
Labels: bug

#1414 Fix printing bug in #1390
  lm_eval/evaluator.py
Labels: bug

#1419 Add multilingual ARC task
  lm_eval/tasks/okapi/arc_multilingual/README.md
  lm_eval/tasks/okapi/arc_multilingual/_arc_yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_ar.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_bn.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_ca.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_da.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_de.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_es.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_eu.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_fr.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_gu.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_hi.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_hr.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_hu.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_hy.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_id.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_it.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_kn.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_ml.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_mr.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_ne.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_nl.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_pt.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_ro.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_ru.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_sk.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_sr.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_sv.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_ta.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_te.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_uk.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_vi.yaml
  lm_eval/tasks/okapi/arc_multilingual/arc_zh.yaml
  lm_eval/tasks/okapi/arc_multilingual/utils.py
Labels: feature request

#1427 Fix: task weighting by subtask size ; update Pooled Stderr formula slightly
  lm_eval/api/metrics.py
  lm_eval/api/registry.py
  lm_eval/tasks/okapi/mmlu_multilingual/_generate_configs.py
  lm_eval/tasks/okapi/truthfulqa_multilingual/utils.py
  tests/test_utils.py
Labels: bug

#1456 Log which subtasks were called with which groups
  lm_eval/evaluator.py
Labels: feature request

#1440 PR fixing the issue #1391 (wrong contexts in the mgsm task)
  lm_eval/tasks/mgsm/direct/mgsm_direct_bn.yaml
  lm_eval/tasks/mgsm/direct/mgsm_direct_de.yaml
  lm_eval/tasks/mgsm/direct/mgsm_direct_en.yaml
  lm_eval/tasks/mgsm/direct/mgsm_direct_es.yaml
  lm_eval/tasks/mgsm/direct/mgsm_direct_fr.yaml
  lm_eval/tasks/mgsm/direct/mgsm_direct_ja.yaml
  lm_eval/tasks/mgsm/direct/mgsm_direct_ru.yaml
  lm_eval/tasks/mgsm/direct/mgsm_direct_sw.yaml
  lm_eval/tasks/mgsm/direct/mgsm_direct_te.yaml
  lm_eval/tasks/mgsm/direct/mgsm_direct_th.yaml
  lm_eval/tasks/mgsm/direct/mgsm_direct_zh.yaml
  lm_eval/tasks/mgsm/en_cot/cot_yaml
  lm_eval/tasks/mgsm/en_cot/mgsm_en_cot_bn.yaml
  lm_eval/tasks/mgsm/en_cot/mgsm_en_cot_de.yaml
  lm_eval/tasks/mgsm/en_cot/mgsm_en_cot_en.yaml
  lm_eval/tasks/mgsm/en_cot/mgsm_en_cot_es.yaml
  lm_eval/tasks/mgsm/en_cot/mgsm_en_cot_fr.yaml
  lm_eval/tasks/mgsm/en_cot/mgsm_en_cot_ja.yaml
  lm_eval/tasks/mgsm/en_cot/mgsm_en_cot_ru.yaml
  lm_eval/tasks/mgsm/en_cot/mgsm_en_cot_sw.yaml
  lm_eval/tasks/mgsm/en_cot/mgsm_en_cot_te.yaml
  lm_eval/tasks/mgsm/en_cot/mgsm_en_cot_th.yaml
  lm_eval/tasks/mgsm/en_cot/mgsm_en_cot_zh.yaml
  lm_eval/tasks/mgsm/gen_yaml.sh
  lm_eval/tasks/mgsm/native_cot/cot_yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_cot_native_bn.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_cot_native_de.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_cot_native_en.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_cot_native_es.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_cot_native_fr.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_cot_native_ja.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_cot_native_ru.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_cot_native_sw.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_cot_native_te.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_cot_native_th.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_cot_native_zh.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_native_cot_bn.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_native_cot_de.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_native_cot_en.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_native_cot_es.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_native_cot_fr.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_native_cot_ja.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_native_cot_ru.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_native_cot_sw.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_native_cot_te.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_native_cot_th.yaml
  lm_eval/tasks/mgsm/native_cot/mgsm_native_cot_zh.yaml
  lm_eval/tasks/mgsm/utils.py
Labels: bug

#1465 Add Gemma support (Add flag to control BOS token usage)
  lm_eval/api/model.py
  lm_eval/models/huggingface.py
  lm_eval/models/neuron_optimum.py
  lm_eval/models/vllm_causallms.py
Labels: feature request

#1441 Refactor `evaluater.evaluate`
  lm_eval/api/model.py
  lm_eval/api/task.py
  lm_eval/evaluator.py
  lm_eval/evaluator_utils.py
  lm_eval/models/huggingface.py
  lm_eval/models/vllm_causallms.py
  lm_eval/utils.py
Labels: feature request
